import type { CopyByLanguage } from '../types';
import type { LegalDocument } from './types';

export const AML_CONTENT: CopyByLanguage<LegalDocument> = {
  pt: {
    lastUpdated: 'Última atualização: 17 de abril de 2025',
    sections: [
      { title: 'VISÃO GERAL AML', paragraphs: [{ text: 'O {nomeBet} está comprometido em cumprir todas as leis e regulamentações de Prevenção à Lavagem de Dinheiro (Anti-Money Laundering - AML) e de Combate ao Financiamento do Terrorismo (CFT) aplicáveis.' }, { text: 'Esta Política AML descreve os procedimentos implementados para prevenir atividades ilícitas e garantir a conformidade com as exigências regulatórias.' }] },
      { title: 'CONFORMIDADE REGULATÓRIA', paragraphs: [{ text: 'O {nomeBet} está em conformidade com:' }, { text: '• Lei nº 9.613/1998 (Lei de Lavagem de Dinheiro do Brasil)', indent: true }, { text: '• Resolução 4.658/2017 do Banco Central do Brasil', indent: true }, { text: '• Regulamentações da Secretaria de Prêmios e Apostas do Ministério da Fazenda', indent: true }, { text: '• FATF (Financial Action Task Force) Recomendações internacionais', indent: true }] },
      { title: 'PROGRAMAS DE COMPLIANCE', paragraphs: [
        { text: 'Know Your Customer (KYC)' }, { text: 'Realizamos verificação rigorosa de identidade de todos os clientes conforme descrito em nossa Política KYC. Isso inclui coleta de informações pessoais, verificação de documentos e análise de elegibilidade.' },
        { text: 'Due Diligence Contínua' }, { text: 'Monitoramos continuamente as contas de clientes para detectar atividades suspeitas. Padrões de transações são analisados para identificar possíveis atividades ilícitas.' },
        { text: 'Screening de Sanções' }, { text: 'Verificamos todos os clientes contra listas de sanções internacionais, incluindo OFAC (Office of Foreign Assets Control) e outras listas de PEP (Politically Exposed Persons).' },
        { text: 'Relatório de Atividades Suspeitas' }, { text: 'Relatamos atividades suspeitas às autoridades competentes, incluindo o Coaf (Conselho de Controle de Atividades Financeiras) conforme obrigado por lei.' },
      ] },
      { title: 'INDICADORES DE ATIVIDADE SUSPEITA', paragraphs: [{ text: 'Atividades que podem ser investigadas incluem:' }, { text: '• Depósitos frequentes seguidos imediatamente por saques', indent: true }, { text: '• Padrões de transações anormais ou inconsistentes com perfil de cliente', indent: true }, { text: '• Transações com jurisdições de alto risco', indent: true }, { text: '• Múltiplas contas com dados similares', indent: true }, { text: '• Recusa em fornecer informações requeridas', indent: true }, { text: '• Documentação fraudulenta ou inconsistências nas informações', indent: true }, { text: '• Transações sem finalidade aparente de jogo', indent: true }] },
      { title: 'LIMITES DE TRANSAÇÃO', paragraphs: [{ text: 'Implementamos limites de transação para monitorar e prevenir lavagem de dinheiro:' }, { text: '• Limite de depósito diário por cliente', indent: true }, { text: '• Limite de saque diário por cliente', indent: true }, { text: '• Limite de transação acumulativa por período', indent: true }, { text: 'Limites podem ser ajustados com base na análise de risco de cada cliente.' }] },
      { title: 'ORIGEM DE FUNDOS', paragraphs: [{ text: 'Todos os depósitos devem ter origem lícita. Você é responsável por confirmar que:' }, { text: '• Os fundos pertencem a você ou a alguém autorizado a depositá-los', indent: true }, { text: '• Os fundos não são provenientes de atividades ilícitas', indent: true }, { text: '• Você pode explicar a origem dos fundos se solicitado', indent: true }, { text: 'Depósitos de origem suspeita serão bloqueados e você pode estar sujeito a relatório às autoridades.' }] },
      { title: 'INVESTIGAÇÕES INTERNAS', paragraphs: [{ text: 'Se detectarmos atividades suspeitas:' }, { text: '• Sua conta pode ser suspensa temporariamente', indent: true }, { text: '• Transações podem ser bloqueadas', indent: true }, { text: '• Podemos solicitar informações adicionais', indent: true }, { text: '• A conta pode ser encerrada permanentemente', indent: true }, { text: '• Ganhos podem ser confiscados', indent: true }, { text: 'Você será notificado se apropriado conforme permitido por lei.' }] },
      { title: 'TERCEIRIZAÇÃO E PARCEIROS', paragraphs: [{ text: 'Todos os fornecedores de serviços e parceiros terceirizados são selecionados com base em seus controles de conformidade AML. Garantimos que cumprem com os mesmos padrões de AML que mantemos.' }] },
      { title: 'POLÍTICAS DE REEMBOLSO', paragraphs: [{ text: 'Reembolsos são processados de volta para o método de pagamento original. Não permitimos redirecionamento de fundos para terceiros, o que ajuda a prevenir lavagem de dinheiro.' }] },
      { title: 'TREINAMENTO E CONSCIENTIZAÇÃO', paragraphs: [{ text: 'Nossa equipe recebe treinamento regular em conformidade AML para garantir que os procedimentos sejam implementados efetivamente e para manter conscientização sobre novos riscos e técnicas de lavagem de dinheiro.' }] },
      { title: 'RELATÓRIOS À COAF', paragraphs: [{ text: 'Somos obrigados a relatar atividades suspeitas ao COAF (Conselho de Controle de Atividades Financeiras) do Brasil. Estes relatórios são confidenciais e protegidos por lei.' }, { text: 'Você não será notificado de relatórios ao COAF conforme exigido por lei para manter a efetividade investigativa.' }] },
    ],
  },
  en: {
    lastUpdated: 'Last updated: April 17, 2025',
    sections: [
      { title: 'AML OVERVIEW', paragraphs: [{ text: '{nomeBet} is committed to complying with all applicable Anti-Money Laundering (AML) and Countering the Financing of Terrorism (CFT) laws and regulations.' }, { text: 'This AML Policy describes the procedures implemented to prevent unlawful activities and ensure compliance with regulatory requirements.' }] },
      { title: 'REGULATORY COMPLIANCE', paragraphs: [{ text: '{nomeBet} complies with:' }, { text: '• Law No. 9,613/1998 (Brazilian Anti-Money Laundering Law)', indent: true }, { text: '• Resolution 4,658/2017 of the Central Bank of Brazil', indent: true }, { text: '• Regulations of the Secretariat of Prizes and Betting of the Ministry of Finance', indent: true }, { text: '• Financial Action Task Force (FATF) international recommendations', indent: true }] },
      { title: 'COMPLIANCE PROGRAMS', paragraphs: [
        { text: 'Know Your Customer (KYC)' }, { text: 'We conduct rigorous identity verification of all customers as described in our KYC Policy. This includes collecting personal information, verifying documents, and assessing eligibility.' },
        { text: 'Ongoing Due Diligence' }, { text: 'We continuously monitor customer accounts to detect suspicious activity. Transaction patterns are analyzed to identify potential unlawful activity.' },
        { text: 'Sanctions Screening' }, { text: 'We screen all customers against international sanctions lists, including OFAC (Office of Foreign Assets Control) and other PEP (Politically Exposed Persons) lists.' },
        { text: 'Suspicious Activity Reporting' }, { text: 'We report suspicious activity to the relevant authorities, including Coaf (Financial Activities Control Council), as required by law.' },
      ] },
      { title: 'SUSPICIOUS ACTIVITY INDICATORS', paragraphs: [{ text: 'Activities that may be investigated include:' }, { text: '• Frequent deposits immediately followed by withdrawals', indent: true }, { text: '• Transaction patterns that are unusual or inconsistent with the customer profile', indent: true }, { text: '• Transactions involving high-risk jurisdictions', indent: true }, { text: '• Multiple accounts with similar data', indent: true }, { text: '• Refusal to provide required information', indent: true }, { text: '• Fraudulent documentation or inconsistent information', indent: true }, { text: '• Transactions with no apparent gaming purpose', indent: true }] },
      { title: 'TRANSACTION LIMITS', paragraphs: [{ text: 'We implement transaction limits to monitor and prevent money laundering:' }, { text: '• Daily deposit limit per customer', indent: true }, { text: '• Daily withdrawal limit per customer', indent: true }, { text: '• Cumulative transaction limit per period', indent: true }, { text: 'Limits may be adjusted based on the risk assessment of each customer.' }] },
      { title: 'SOURCE OF FUNDS', paragraphs: [{ text: 'All deposits must have a lawful source. You are responsible for confirming that:' }, { text: '• The funds belong to you or to someone authorized to deposit them', indent: true }, { text: '• The funds do not arise from unlawful activities', indent: true }, { text: '• You can explain the source of the funds if requested', indent: true }, { text: 'Deposits from suspicious sources will be blocked, and you may be reported to the authorities.' }] },
      { title: 'INTERNAL INVESTIGATIONS', paragraphs: [{ text: 'If we detect suspicious activity:' }, { text: '• Your account may be temporarily suspended', indent: true }, { text: '• Transactions may be blocked', indent: true }, { text: '• We may request additional information', indent: true }, { text: '• The account may be permanently closed', indent: true }, { text: '• Winnings may be forfeited', indent: true }, { text: 'You will be notified where appropriate and as permitted by law.' }] },
      { title: 'OUTSOURCING AND PARTNERS', paragraphs: [{ text: 'All service providers and outsourced partners are selected based on their AML compliance controls. We ensure that they meet the same AML standards that we maintain.' }] },
      { title: 'REFUND POLICIES', paragraphs: [{ text: 'Refunds are processed back to the original payment method. We do not permit funds to be redirected to third parties, which helps prevent money laundering.' }] },
      { title: 'TRAINING AND AWARENESS', paragraphs: [{ text: 'Our team receives regular AML compliance training to ensure procedures are implemented effectively and to maintain awareness of new money laundering risks and techniques.' }] },
      { title: 'REPORTS TO COAF', paragraphs: [{ text: 'We are required to report suspicious activities to Brazil’s COAF (Financial Activities Control Council). These reports are confidential and protected by law.' }, { text: 'You will not be notified of reports to COAF, as required by law to preserve their investigative effectiveness.' }] },
    ],
  },
  es: {
    lastUpdated: 'Última actualización: 17 de abril de 2025',
    sections: [
      { title: 'VISIÓN GENERAL DE AML', paragraphs: [{ text: '{nomeBet} se compromete a cumplir todas las leyes y regulaciones aplicables de Prevención de Lavado de Dinero (Anti-Money Laundering, AML) y de Lucha contra el Financiamiento del Terrorismo (CFT).' }, { text: 'Esta Política AML describe los procedimientos implementados para prevenir actividades ilícitas y garantizar el cumplimiento de los requisitos regulatorios.' }] },
      { title: 'CUMPLIMIENTO REGULATORIO', paragraphs: [{ text: '{nomeBet} cumple con:' }, { text: '• Ley n.º 9.613/1998 (Ley brasileña de Lavado de Dinero)', indent: true }, { text: '• Resolución 4.658/2017 del Banco Central de Brasil', indent: true }, { text: '• Regulaciones de la Secretaría de Premios y Apuestas del Ministerio de Hacienda', indent: true }, { text: '• Recomendaciones internacionales del GAFI (Grupo de Acción Financiera Internacional)', indent: true }] },
      { title: 'PROGRAMAS DE CUMPLIMIENTO', paragraphs: [
        { text: 'Know Your Customer (KYC)' }, { text: 'Realizamos una rigurosa verificación de identidad de todos los clientes conforme se describe en nuestra Política KYC. Esto incluye la recopilación de información personal, la verificación de documentos y el análisis de elegibilidad.' },
        { text: 'Debida Diligencia Continua' }, { text: 'Supervisamos continuamente las cuentas de los clientes para detectar actividades sospechosas. Se analizan los patrones de transacción para identificar posibles actividades ilícitas.' },
        { text: 'Control de Sanciones' }, { text: 'Verificamos a todos los clientes frente a listas internacionales de sanciones, incluidas OFAC (Office of Foreign Assets Control) y otras listas de PEP (Personas Políticamente Expuestas).' },
        { text: 'Reporte de Actividades Sospechosas' }, { text: 'Reportamos las actividades sospechosas a las autoridades competentes, incluido el Coaf (Consejo de Control de Actividades Financieras), según lo exige la ley.' },
      ] },
      { title: 'INDICADORES DE ACTIVIDAD SOSPECHOSA', paragraphs: [{ text: 'Las actividades que pueden ser investigadas incluyen:' }, { text: '• Depósitos frecuentes seguidos inmediatamente de retiros', indent: true }, { text: '• Patrones de transacción anormales o inconsistentes con el perfil del cliente', indent: true }, { text: '• Transacciones con jurisdicciones de alto riesgo', indent: true }, { text: '• Múltiples cuentas con datos similares', indent: true }, { text: '• Negativa a proporcionar la información requerida', indent: true }, { text: '• Documentación fraudulenta o inconsistencias en la información', indent: true }, { text: '• Transacciones sin una finalidad de juego aparente', indent: true }] },
      { title: 'LÍMITES DE TRANSACCIÓN', paragraphs: [{ text: 'Implementamos límites de transacción para supervisar y prevenir el lavado de dinero:' }, { text: '• Límite diario de depósito por cliente', indent: true }, { text: '• Límite diario de retiro por cliente', indent: true }, { text: '• Límite acumulativo de transacciones por período', indent: true }, { text: 'Los límites pueden ajustarse con base en el análisis de riesgo de cada cliente.' }] },
      { title: 'ORIGEN DE FONDOS', paragraphs: [{ text: 'Todos los depósitos deben tener un origen lícito. Usted es responsable de confirmar que:' }, { text: '• Los fondos le pertenecen a usted o a alguien autorizado a depositarlos', indent: true }, { text: '• Los fondos no provienen de actividades ilícitas', indent: true }, { text: '• Puede explicar el origen de los fondos si se le solicita', indent: true }, { text: 'Los depósitos de origen sospechoso serán bloqueados y usted puede quedar sujeto a un reporte ante las autoridades.' }] },
      { title: 'INVESTIGACIONES INTERNAS', paragraphs: [{ text: 'Si detectamos actividades sospechosas:' }, { text: '• Su cuenta puede suspenderse temporalmente', indent: true }, { text: '• Las transacciones pueden bloquearse', indent: true }, { text: '• Podemos solicitar información adicional', indent: true }, { text: '• La cuenta puede cerrarse permanentemente', indent: true }, { text: '• Las ganancias pueden ser confiscadas', indent: true }, { text: 'Se le notificará cuando sea apropiado y esté permitido por la ley.' }] },
      { title: 'TERCERIZACIÓN Y SOCIOS', paragraphs: [{ text: 'Todos los proveedores de servicios y socios externos se seleccionan con base en sus controles de cumplimiento AML. Garantizamos que cumplen los mismos estándares AML que mantenemos.' }] },
      { title: 'POLÍTICAS DE REEMBOLSO', paragraphs: [{ text: 'Los reembolsos se procesan de vuelta al método de pago original. No permitimos el redireccionamiento de fondos a terceros, lo que ayuda a prevenir el lavado de dinero.' }] },
      { title: 'CAPACITACIÓN Y CONCIENTIZACIÓN', paragraphs: [{ text: 'Nuestro equipo recibe capacitación periódica en cumplimiento AML para garantizar que los procedimientos se implementen de forma eficaz y para mantener la concientización sobre nuevos riesgos y técnicas de lavado de dinero.' }] },
      { title: 'REPORTES AL COAF', paragraphs: [{ text: 'Estamos obligados a reportar actividades sospechosas al COAF (Consejo de Control de Actividades Financieras) de Brasil. Estos reportes son confidenciales y están protegidos por ley.' }, { text: 'No se le notificará sobre los reportes al COAF, según lo exige la ley para preservar su eficacia investigativa.' }] },
    ],
  },
};
